$('.owl-block').owlCarousel({
    loop:true,
    margin:0,
    autoplay:false,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})

$('.carouse-product').owlCarousel({
    loop:true,
    margin:10,
    autoplay:false,
    nav:true,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})

